// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sJ-Rkm0qwS5VrUWHS2jLEjF2DS9brWE',
    appId: '1:72118664378:web:a477b0eaaf8df557bed683',
    messagingSenderId: '72118664378',
    projectId: 'productivity-app-8ca50',
    authDomain: 'productivity-app-8ca50.firebaseapp.com',
    storageBucket: 'productivity-app-8ca50.appspot.com',
    measurementId: 'G-S1VVEYLPX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhIUxiO4Raiu6P4ziCL3mNOBimJNdAqw',
    appId: '1:72118664378:android:8907c8563376e011bed683',
    messagingSenderId: '72118664378',
    projectId: 'productivity-app-8ca50',
    storageBucket: 'productivity-app-8ca50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHsU-Z90HAYX-fgUP9HSwlnkkyQT6p7E',
    appId: '1:72118664378:ios:b5b6e8041424fe7dbed683',
    messagingSenderId: '72118664378',
    projectId: 'productivity-app-8ca50',
    storageBucket: 'productivity-app-8ca50.appspot.com',
    iosClientId: '72118664378-2vgqs7e9ue3nh0eslms7sonhqjn0kjhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityApp',
  );
}
